version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    expose:
      - "3000"
    networks:
      - web
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/certificates:/etc/letsencrypt
      - ./app:/usr/src/app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    depends_on:
      - app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/certificates:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - web
    restart: always

networks:
  web:
    driver: bridge
