FROM certbot/certbot

# Rodar o certbot para gerar o certificado inicial
CMD ["certbot", "certonly", "--standalone", "--preferred-challenges", "http", "--email", "seu_email@dominio.com", "--agree-tos", "--no-eff-email", "-d", "bots.sharpos.ai"]
